const PDFDocument = require("pdfkit");
const cloudinary = require("../config/cloudinary");
const streamifier = require("streamifier");

/**
 * Generate a payment receipt PDF buffer in memory.
 */
const generateReceiptBuffer = ({ patient, appointment, payment, doctor }) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const buffers = [];

    doc.on("data", (chunk) => buffers.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    const teal = "#0d9488";
    const darkGray = "#1f2937";
    const gray = "#6b7280";

    // Header bar
    doc.rect(0, 0, doc.page.width, 80).fill(teal);
    doc.fillColor("white").fontSize(22).font("Helvetica-Bold").text("CareLine360", 50, 20);
    doc.fontSize(10).font("Helvetica").text("Smart Healthcare & Emergency System", 50, 46);

    doc.fillColor(darkGray).moveDown(3);

    // Title
    doc.fontSize(16).font("Helvetica-Bold").fillColor(teal).text("PAYMENT RECEIPT", { align: "center" });
    doc.moveDown(0.5);

    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(teal).lineWidth(1).stroke();
    doc.moveDown(0.5);

    // Receipt info
    const startY = doc.y;

    // Left: Patient info
    doc.fontSize(10).font("Helvetica-Bold").fillColor(teal).text("PATIENT", 50, startY);
    doc.fillColor(darkGray).font("Helvetica")
      .text(patient.fullName || "Patient", 50, doc.y + 4)
      .text(`Email: ${patient.email || "N/A"}`, 50, doc.y + 2);

    // Right: Receipt date
    doc.fontSize(10).font("Helvetica-Bold").fillColor(teal).text("RECEIPT", 320, startY);
    doc.fillColor(darkGray).font("Helvetica")
      .text(`Date: ${new Date().toLocaleDateString("en-GB")}`, 320, startY + 16)
      .text(`Ref: ${payment.transactionRef || "N/A"}`, 320, startY + 30);

    doc.y = startY + 60;
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e5e7eb").lineWidth(0.5).stroke();
    doc.moveDown(1);

    // Appointment details
    doc.fontSize(11).font("Helvetica-Bold").fillColor(teal).text("APPOINTMENT DETAILS");
    doc.moveDown(0.3);
    doc.fontSize(10).font("Helvetica").fillColor(darkGray);
    doc.text(`Doctor: Dr. ${doctor?.fullName || "N/A"}`);
    doc.text(`Specialization: ${doctor?.specialization || "General"}`);
    doc.text(`Date: ${appointment.date ? new Date(appointment.date).toLocaleDateString("en-GB") : "N/A"}`);
    doc.text(`Time: ${appointment.time || "N/A"}`);
    doc.text(`Type: ${appointment.consultationType || "N/A"}`);
    doc.moveDown(1);

    // Payment details
    doc.fontSize(11).font("Helvetica-Bold").fillColor(teal).text("PAYMENT DETAILS");
    doc.moveDown(0.3);
    doc.fontSize(10).font("Helvetica").fillColor(darkGray);
    doc.text(`Amount: LKR ${payment.amount?.toLocaleString("en-LK", { minimumFractionDigits: 2 }) || "0.00"}`);
    doc.text(`Method: ${payment.method || "N/A"}`);
    doc.text(`Status: ${payment.status || "N/A"}`);
    doc.text(`Transaction Ref: ${payment.transactionRef || "N/A"}`);
    if (payment.verifiedAt) {
      doc.text(`Verified: ${new Date(payment.verifiedAt).toLocaleString()}`);
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#e5e7eb").lineWidth(0.5).stroke();
    doc.moveDown(1);

    // Total
    doc.fontSize(14).font("Helvetica-Bold").fillColor(teal)
      .text(`Total Paid: LKR ${payment.amount?.toLocaleString("en-LK", { minimumFractionDigits: 2 }) || "0.00"}`, { align: "right" });

    // Footer
    const footerY = doc.page.height - 50;
    doc.fontSize(8).fillColor(gray)
      .text("This receipt was generated by CareLine360 | For queries, contact support@careline360.com", 50, footerY, {
        align: "center",
        width: doc.page.width - 100,
      });

    doc.end();
  });
};

/**
 * Upload a receipt PDF buffer to Cloudinary.
 */
const uploadReceiptBuffer = (pdfBuffer) => {
  if (!process.env.CLOUDINARY_CLOUD_NAME) {
    return Promise.resolve(null);
  }
  return new Promise((resolve, reject) => {
    try {
      const uploadStream = cloudinary.uploader.upload_stream(
        {
          folder: "careline360/receipts",
          resource_type: "auto",
          format: "pdf",
          public_id: `receipt_${Date.now()}`,
          timeout: 30000,
        },
        (error, result) => {
          if (error) return reject(error);
          resolve({ fileUrl: result.secure_url, publicId: result.public_id });
        }
      );
      uploadStream.on("error", (err) => reject(err));
      const readStream = streamifier.createReadStream(pdfBuffer);
      readStream.on("error", (err) => reject(err));
      readStream.pipe(uploadStream);
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateReceiptBuffer, uploadReceiptBuffer };
